#!/usr/bin/env bash
# Cluster-side: generate Fig 7 (bias maps) for the 12 h paper.
#
# Produces figs/fig7_bias_maps_12h.{png,pdf} — 7 models × 6 channels at
# τ=6 h (mid 12 h interval, hardest case).
#
# Implementation note: this script is a placeholder pointing to the
# generic figure script tools/figs/make_fig7_bias_maps_12h.py, which
# (until cluster execution) does not exist locally. It must be authored
# on the cluster where memmap dataset + ckpts are available.
#
# Pseudo-code for the figure generator:
#   for each model in 7 strict-ep10 ckpts:
#     load ckpt → model
#     for each (x0, xT, target) in sampled subset of 2020 test:
#       pred = model(x0, xT, τ=0.5, cond=12.0)
#       bias = pred − target
#     average bias across windows → per-channel map
#   plot 7×6 grid of bias maps (lon × lat) with shared colorbar per row
#
# Channels: t2m, mslp, u10, v10 (surface) + T850, Z700 (PL)
# Sample size: ~96 windows × 4 days/month = enough for stable maps
# ETA on B300: ~ 20 min total.
set -euo pipefail

WTI_ROOT="${WTI_ROOT:-/workspace/code/wti}"
FIG_DIR="${FIG_DIR:-${WTI_ROOT}/figs}"

mkdir -p "${FIG_DIR}"

cat <<'INSTRUCTIONS'
=== Fig 7 (bias maps 12 h) launch ===

This script is a launcher placeholder. The 12 h bias-map figure
generator has not yet been authored — the 6 h version
(figs/fig7_bias_maps.png) was generated by an unrecovered script.

To produce figs/fig7_bias_maps_12h.{png,pdf}:

  1. Author tools/figs/make_fig7_bias_maps_12h.py with the following
     structure (adapt from existing make_fig11_*.py if available):

       - Load memmap dataset (ERA5MemmapDataset, year=2020, 4 d/mo).
       - For each model in the 7 strict-ep10 ckpts (see
         docs/eval_history.md table for paths):
           - Load checkpoint via WeatherHermiteLightningModule (or
             dedicated VFI path for ATM-VFI).
           - For each window, run model at τ=0.5 (mid-window).
           - Accumulate bias = pred − target per pixel per channel.
       - Take the mean bias across all windows.
       - Render a 7×6 grid (rows = models, cols = channels {t2m,
         mslp, u10, v10, T850, Z700}) with cartopy + RdBu_r cmap,
         shared per-column normalisation (or per-row to keep
         physically meaningful magnitudes), and contour overlays for
         major coastlines.

  2. Run on B300: ETA ~20 min.

  3. rsync figs/fig7_bias_maps_12h.* back to local repo.

INSTRUCTIONS

echo "[run_fig7_bias_maps_12h] No-op placeholder. See instructions above."
INSTRUCTIONS
